var objIdioma={
	"data":[
		{"sel":".tProducto", "content": ["Productos", "Products"]},
		{"sel":".tCatalogo", "content": ["Catálogo de productos", "Products Catalog"]},
		{"sel":".tChoco", "content": ["Chocolate", "Chocolate"]},
		{"sel":".tFondant", "content": ["Fondant", "Fondant"]},
		{"sel":".tgelatina", "content": ["Gelatina artística", "Artistic Jelly"]},
		{"sel":".tGalleta", "content": ["Galletas decoradas", "Decorates cookies"]},
		{"sel":".tBombon", "content": ["Bombón", "Marshmallow"]},
		{"sel":".tPastel", "content": ["Pastel de crema", "Cream cake"]},
		{"sel":".tPanaderia", "content": ["Panadería", "Bakery"]},
		{"sel":".tEmpresa", "content": ["Empresa", "About us"]},
		{"sel":".tVideorecetas", "content": ["Videorecetas", "Video recipes"]},
		{"sel":".tContacto", "content": ["Contacto", "Contact"]},
		{"sel":".tGaleria", "content": ["Galeria", "Gallery"]},
		{"sel":".tTodosProductos", "content": ["Todos los Productos", "All Products"]},
		{"sel":".tContactoB", "content": ["Contacto", "Contact"]},
		{"sel":".tGaleriaT", "content": ["¡Deja volar tu imaginación! Encuentra tu estilo y crea hermosos proyectos utilizando los productos de Ma Baker and Chef.", "Let your imagination fly! Find your style and create beautiful projects using Ma Baker and Chef products."]},
		{"sel":".tTodosProductosT", "content": ["En Ma Baker and Chef encontrarás una amplia gama de productos y colores para darle un toque único a todas tus creaciones.", "In Ma Baker and Chef you'll find a wide range of products and colors, to give to your creations an unique touch."]},
		{"sel":".tContactoT", "content": ["¿Tienes alguna duda o sugerencia? Rellena el formulario con tus inquietudes, y te responderemos a la brevedad.", "Do you have any comment or suggestion? Fill the form with your questions and we'll answer you as soon as possible"]},
		{"sel":"#chocolate .texto .texto1", "content": ["Chocolate", "Chocolate"]},
		{"sel":"#chocolate .texto .texto2", "content": ["BOMBERIA", ""]},
		{"sel":"#gelatina .texto .texto1", "content": ["Gelatina", "Artistic"]},
		{"sel":"#gelatina .texto .texto2", "content": ["ARTÍSTICA", "JELLY"]},
		{"sel":"#galletas .texto .texto1", "content": ["Galletas", "Decorates"]},
		{"sel":"#galletas .texto .texto2", "content": ["DECORADAS", "COOKIES"]},
		{"sel":"#fondant .texto .texto1", "content": ["Fondant", "Fondant"]},
		{"sel":"#bombon .texto .texto1", "content": ["Bombón", "Marshmallow"]},
		{"sel":"#bombon .texto .texto2", "content": ["MALVAVISCOS", ""]},
		{"sel":"#pastel .texto .texto1", "content": ["Pastel", "Cream"]},
		{"sel":"#pastel .texto .texto2", "content": ["DE CREMA", "CAKE"]},
		{"sel":"#panaderia .texto .texto1", "content": ["Panaderia", "Bakery"]},
		{"sel":"#postres .texto .texto1", "content": ["Postres", "Desserts"]},
		{"sel":"#ingredientes .texto .texto1", "content": ["Ingredientes", "Ingredients"]},
		{"sel":"#moldes .texto .texto1", "content": ["Moldes", "Molds"]},
		{"sel":"#btnTodosProductos", "content": ["· TODOS<strong> NUESTROS </strong>PRODUCTOS ·", "· ALL<strong> OUR </strong>PRODUCTS ·"]},
		{"sel":"#tTodosProductos", "content": ["Todos los Productos", "All Products"]},
		{"sel":".tChoco2", "content": ["Bomboneria", ""]},
		{"sel":".tGelatinaS", "content": ["Gelatina", "Artistic"]},
		{"sel":".tGelatinaS2", "content": ["Artística", "Jelly"]},
		{"sel":".tGalletaS", "content": ["Galletas", "Decorates"]},
		{"sel":".tGalletaS2", "content": ["Decoradas", "Cookies"]},
		{"sel":".tBombonS", "content": ["Bombón", "Marshmallow"]},
		{"sel":".tBombonS2", "content": ["Malvaviscos", ""]},
		{"sel":"#tProductoTexto", "content": ["Encuentra la gama de productos necesarios por categoria", "Find the necessary product range by category."]},
		{"sel":"#tProducto", "content": ["Productos", "Products"]},
		{"sel":".tPastelS", "content": ["Pastel", "Cream"]},
		{"sel":".tPastelS2", "content": ["de Crema", "Cake"]},
		{"sel":".tPanaderiaS", "content": ["Panaderia", "Bakery"]},
		{"sel":"#acercaDe", "content": ["<strong>Ma Baker and Chef</strong> es una empresa con más de 10 años de experiencia dedicada a la fabricación, comercialización, importación y exportación de productos para la industria panadera y repostera principalmente, además de brindar a otros segmentos el diseño de sus colores y sabores de alta calidad como materias primas para sus productos terminados. <br><br><strong>Ma Baker and Chef</strong> tiene el compromiso con sus clientes de ofrecerles su tecnología para realzar sus productos haciéndolos más atractivos a la vista y al gusto con el objetivo de lograr expandir sus negocios.", "<strong>Ma Baker and Chef</strong> is an enterprise with more than 10 years of experience in manufacturing, commercialization, import and export mainly of bakery and pastry products, besides bringing to other sectors the design of its high quality colors and flavors as raw materials for their final products.<br><br><strong>Ma Baker and Chef</strong> has a strong compromise with their costumers of bringing them its technology to enhance their products, making them more attractive to the eye and taste, in order to spread out their organizations."]},
		{"sel":"#tObjetivo", "content": ["« OBJETIVOS »", "« GOALS »"]},
		{"sel":"#simple1", "content": ["Ofrecer sus productos a empresas y negocios que se desarrollan en el mercado de la repostería, pastelería y panadería, con el fin de facilitar de forma integral el desempeño de las operaciones de nuestros clientes. Con capacidad de respuesta para atender eficazmente a todo requerimiento, impulsando el desarrollo de nuestros clientes y aportando crecimiento a la industria.", "Offer its products to enterprises and businesses currently developing in the pastry and bakery market, in order to make integrally easier the performance of their procedures. With a very effective responsiveness to attend every requirement, enhancing the development of our customers, and providing growth to the industry. "]},
		{"sel":"#enfasisLight", "content": ["LA ÉTICA, PROFESIONALISMO, RESPETO, HONRADEZ, <br> TRANSPARENCIA  Y COMPROMISO CON UN RESPETO TOTAL <br> A LOS VALORES Y POLÍTICAS DE NUESTROS CLIENTES. <br> <strong>“CALIDAD Y RESPUESTA INMEDIATA”</strong>", "Ethics, professionalism, respect, honesty,<br> transparency and commitment with a complete respect<br> to the politics and the values of our customers.<br><br><strong>“Quality and immediate response”</strong>"]},
		{"sel":"#tMision", "content": [" « MISIÓN » ", "« MISSION »"]},
		{"sel":".tMisionTxt", "content": ["Apoyar a las empresas y negocios en la proyección y promoción de sus productos, así como en el crecimiento de sus servicios. Así mismo, ser promotores de su crecimiento permanente, participando conjuntamente en el desarrollo de conceptos e ideas que sean creativas y funcionales.", "Support the enterprises and small businesses in the projection and promotion of their products, as well as in the growth of their services.  Also, being the promoters of their permanent growth, participating together in the developing of functional & creative concepts and ideas."]},
		{"sel":".tSuscribete", "content": ["Suscribete a nuestro canal", "Subscribe to our channel"]},
		{"sel":".tFrase", "content": ["¿Buscas <strong>Sabor</strong> y <strong>Color?</strong> <br> <strong>¡Contactanos!</strong>", "¿Searching <strong>Color</strong> and <strong>Flavor?</strong> <br> <strong>¡Contact us!</strong>"]},
		{"sel":"#tFormulario", "content": ["A continuación le presentamos un formulario de contacto con el cual podrá enviarnos sus datos y con mucho gusto nos contactaremos con usted a la brevedad", "Below you will find a contact form where you can send us your information we’ll be very pleased to get in touch with you as soon as possible"]},
		{"sel":".tNombre", "content": ["Nombre", "Name"]},
		{"sel":".tCiudad", "content": ["Ciudad", "City"]},
		{"sel":".tEstado", "content": ["Estado", "State"]},
		{"sel":"#tPais", "content": ["Pais", "Country"]},
		{"sel":"#tCP", "content": ["C.P.", "Zip"]},
		{"sel":".tCorreo", "content": ["Correo", "E-Mail"]},
		{"sel":"#tAtencion", "content": ["Atención", "Attention"]},
		{"sel":"#tDistribuidor", "content": ["Distribuidor", "Distributor"]},
		{"sel":"#tMayorista", "content": ["Mayorista", "Wholesaler"]},
		{"sel":"#tPublico", "content": ["Publico", "Public"]},
		{"sel":"#tOtro", "content": ["Otro", "Others"]},
		{"sel":"#tCometarios", "content": ["Comentarios", "Comments"]},
		{"sel":"#visitanosTxt", "content": ["... o <strong>visitanos </strong> en ", "... or <strong>visit us</strong> in "]},
		{"sel":"#tAcetato", "content": ["Acetato", "Acetate"]},
		{"sel":"#tAcetato2", "content": ["", "strips"]},
		{"sel":"#tboton", "content": ["enviar", "send"]},
		{"sel":"#tBenzonato", "content": ["Benzonato", "Sodium"]},
		{"sel":"#tBenzonato2", "content": ["", "Benzoate"]},
		{"sel":"#tAcido", "content": ["Acido", "Citric"]},
		{"sel":"#tAcido2", "content": ["Citrico", "Acid"]},
		{"sel":"#tBrillo", "content": ["Brillo para", "Fruit and Bread"]},
		{"sel":"#tBrillo2", "content": ["Pan y Fruta", "Gloss"]},
		{"sel":"#tCaramelo", "content": ["Caramelo", "Liquid Caramel"]},
		{"sel":"#tCaramelo2", "content": ["Liquido", "Color"]},
		{"sel":"#tCoberturaDona", "content": ["Cobertura", "Donut Fondant"]},
		{"sel":"#tCoberturaDona2", "content": ["para Dona", "Covering"]},
		{"sel":"#tCoberturaChoco", "content": ["Cobertura", "Chocolate Flavored"]},
		{"sel":"#tCoberturaChoco2", "content": ["para Chocolate", "Cover"]},
		{"sel":"#tCocoa", "content": ["Cocoa", "Alkaline"]},
		{"sel":"#tCocoa2", "content": ["Alcalina", "Cocoa"]},
		{"sel":"#tColorChoco", "content": ["Color", "Cocoa Butter"]},
		{"sel":"#tColorChoco2", "content": ["para Chocolate", "Colors"]},
		{"sel":"#tColorPolvo", "content": ["Color", "Bread Powder"]},
		{"sel":"#tColorPolvo2", "content": ["en Polvo", "Colors"]},
		{"sel":"#tCortadores", "content": ["Cortadores", "Fondant and Cookies"]},
		{"sel":"#tCortadores2", "content": ["", "Cutters"]},
		{"sel":"#tCremor", "content": ["Cremor", "Tartar"]},
		{"sel":"#tCremor2", "content": ["Tartaro", "Cream"]},
		{"sel":"#tDesmoldante", "content": ["Desmoldante", "Releasing"]},
		{"sel":"#tDesmoldante2", "content": ["en Spray", "Agent"]},
		{"sel":"#tDiamantina6", "content": ["Diamantina", "6gr."]},
		{"sel":"#tDiamantina62", "content": ["6g", "Glitter"]},
		{"sel":"#tDiamantina7", "content": ["Diamantina", "7gr."]},
		{"sel":"#tDiamantina72", "content": ["7g", "Glitter"]},
		{"sel":"#tCMC", "content": ["Endurecedor de Fondant", "Fondant Hardener"]},
		{"sel":"#tCMC2", "content": ["CMC", "CMC"]},
		{"sel":"#tGlicerina", "content": ["Glicerina", "Glycerin"]},
		{"sel":"#tGlucosa", "content": ["Glucosa", "Glucose"]},
		{"sel":"#tLectina", "content": ["Lectina", "Soy"]},
		{"sel":"#tLectina2", "content": ["de Soya", "Lecithin"]},
		{"sel":"#tMatizadores", "content": ["Matizadores", "Matting"]},
		{"sel":"#tMermelada", "content": ["Mermelada", "Baking"]},
		{"sel":"#tMermelada2", "content": ["Horneable", "Jams"]},
		{"sel":"#tMoldesPoli", "content": ["Moldes", "Polycarbonate"]},
		{"sel":"#tMoldesPoli2", "content": ["de Policarbonato", "Molds"]},
		{"sel":"#tMoldesSilicona", "content": ["Moldes", "Silicone"]},
		{"sel":"#tMoldesSilicona2", "content": ["de Silicona", "Molds"]},
		{"sel":"#tTransferChoco", "content": ["Transfer", "Chocolate"]},
		{"sel":"#tTransferChoco2", "content": ["para Chocolate", "transfer"]},
		{"sel":"#tMoldesTruffly", "content": ["Moldes", "Truffly Silicone"]},
		{"sel":"#tMoldesTruffly2", "content": ["Truffly", "Molds"]},
		{"sel":"#tPectina", "content": ["Pectina", "Pectin"]},
		{"sel":"#tPegamento", "content": ["Pegamento", "Gum Paste and Fondant"]},
		{"sel":"#tPegamento2", "content": ["para Fondant", "Glue"]},
		{"sel":"#tPerlasD", "content": ["Perlas", "Glittered"]},
		{"sel":"#tPerlasD2", "content": ["Diamantadas", "Pearls"]},
		{"sel":"#tPerlasN", "content": ["Perlas", "Pearly"]},
		{"sel":"#tPerlasN2", "content": ["Nacaradas", "Pearls"]},
		{"sel":"#tPintaColorD", "content": ["PintaColor", "Glittered color"]},
		{"sel":"#tPintaColorD2", "content": ["Diamantado", "paintings"]},
		{"sel":"#tPintaColorM", "content": ["PintaColor", "Metallic Color"]},
		{"sel":"#tPintaColorM2", "content": ["Metalico", "Paintings"]},
		{"sel":"#tPlumones", "content": ["Plumones", "Edible"]},
		{"sel":"#tPlumones2", "content": ["Comestibles", "Markers"]},
		{"sel":"#tRelleno", "content": ["Relleno", "Ganache"]},
		{"sel":"#tRelleno2", "content": ["tipo Ganache", "Fillings"]},
		{"sel":"#tSaborPan", "content": ["Sabor", "Bread"]},
		{"sel":"#tSaborPan2", "content": ["para Pan", "Flavors"]},
		{"sel":"#tSaborGanache", "content": ["Sabores para", "Ganache"]},
		{"sel":"#tSaborGanache2", "content": ["Ganache", "flavors"]},
		{"sel":"#tSprayOro", "content": ["Oro", "Gold"]},
		{"sel":"#tTapete", "content": ["Tapete", "Fondant"]},
		{"sel":"#tTapete2", "content": ["Para Fondant", "Spreader Rug"]},
		{"sel":"#tVainilla", "content": ["Vainilla", "Dark"]},
		{"sel":"#tVainilla2", "content": ["Oscura", "Vainilla"]},
		{"sel":"#tSprayPlata", "content": ["Plata", "Silver"]},
		{"sel":"#tCoberturaChiclosa", "content": ["Cobertura", "Taffy"]},
		{"sel":"#tCoberturaChiclosa2", "content": ["Chiclosa", "Cover"]},
		{"sel":"#tFlan", "content": ["Flan", "Custard"]},
		{"sel":"#tFlan2", "content": ["en Polvo", "Powder"]},
		{"sel":"#tFuente", "content": ["Fuente", "Chocolate"]},
		{"sel":"#tFuente2", "content": ["de Chocolate", "Fountain"]},
		{"sel":"#tGubias", "content": ["Gubias", "Gouges"]},
		{"sel":"#tMerengue", "content": ["Merengue", "Meringue"]},
		{"sel":"#tMerengue2", "content": ["", "Powder"]},
		{"sel":"#tSaborGelatina", "content": ["Sabores para", "Jelly"]},
		{"sel":"#tSaborGelatina2", "content": ["Sabores para", "Flavors"]},

	]
}
// Te deje dos ejemplos Ema, el primero seria para cuando vas a remplazar un tag <img src="bla bla">, en este caso
// tendras que agregarle la clase al img ej: <img class="selector" src=""/>
// el segundo que es el que esta ccasi en todo el sitio es para remplazar un background image por lo que hay que 
// agregar con todo y el url();
var objImagenesL={
	"data":[
		{"sel":".tProducto", "img": ["shared/img/imagenEspanol.jpg", "shared/img/imagenIngles.jpg"]}, /* para un img*/
		{"sel":"#Vchocolate", "img": ["url(shared/img/Videorecetas/chocolateG.jpg)", "url(shared/img/Videorecetas/chocolateGI.jpg)"]}, /* para un background image*/
		{"sel":"#Vfondant", "img": ["url(shared/img/Videorecetas/fondantG.jpg)", "url(shared/img/Videorecetas/fondantGi.jpg)"]}, 
		{"sel":"#Vgelatina", "img": ["url(shared/img/Videorecetas/gelatinaG.jpg)", "url(shared/img/Videorecetas/gelatinaGi.jpg)"]}, 
		{"sel":"#Vpanaderia", "img": ["url(shared/img/Videorecetas/panaderiaG.jpg)", "url(shared/img/Videorecetas/panaderiaGi.jpg)"]}, 
		{"sel":"#Vgalletas", "img": ["url(shared/img/Videorecetas/galletas.jpg)", "url(shared/img/Videorecetas/galletasi.jpg)"]}, 
		{"sel":"#vPastel", "img": ["url(shared/img/Videorecetas/pastel.jpg)", "url(shared/img/Videorecetas/pasteli.jpg)"]}, 
		{"sel":"#VcupCakes", "img": ["url(shared/img/Videorecetas/cupcakes.jpg)", "url(shared/img/Videorecetas/cupcakesi.jpg)"]}, 
		{"sel":"#Veventos", "img": ["url(shared/img/Videorecetas/eventos.jpg)", "url(shared/img/Videorecetas/eventosi.jpg)"]}
	]
}


function cambiaIdioma () {
	for(i in objIdioma.data){
		var selector=objIdioma.data[i].sel;
		var content=objIdioma.data[i].content[lang];
		$(selector).html(content);
	}
	for(i in objImagenesL.data){
		var selector=objImagenesL.data[i].sel;
		var img=objImagenesL.data[i].img[lang];
		if (img.indexOf("url")>=0) {
			$(selector).css("background-image", img);
		}else{
			$(selector).attr("src",img);
		}
	}
}
